export default {
  event: '任意事件都将触发 --- 自定义事件',
  err: 'some error --- 自定义事件',
  check_run: '检查运行活动已发生。 活动类型在有效负载对象的 action 属性中指定',
  check_suite: '检查套件活动已发生。 活动类型在有效负载对象的 action 属性中指定',
  code_scanning_alert: '与仓库中的代码扫描警报相关的活动。 活动类型在有效负载对象的操作属性中指定',
  commit_comment: '提交评论已创建',
  content_reference: '新的内容引用为 created',
  create: 'Git 分支或标签已创建',
  delete: 'Git 分支或标签已删除',
  deploy_key: '在仓库中添加或删除部署密钥',
  deployment: '已创建部署',
  deployment_status: '部署状态更新',
  discussion: '与讨论相关的活动',
  discussion_comment: '与讨论中的评论相关的活动',
  fork: '复制仓库',
  github_app_authorization: '当有人撤销对 GitHub 应用程序 的授权时，将发生此事件',
  gollum: '创建或更新 wiki 页面',
  installation: "与 GitHub 应用程序安装相关的活动",
  installation_repositories: "与要添加到 GitHub 应用程序安装中的仓库相关的活动",
  issue_comment: "发表issue评论",
  issues: "issue关闭或打开",
  label: "与标签相关的活动",
  marketplace_purchase: '与 GitHub Marketplace 购买相关的活动',
  member: '与仓库协作者相关的活动',
  membership: '与团队成员相关的活动',
  meta: '配置此事件的 web 挂钩已被删除',
  milestone: '里程碑相关',
  organization: '与组织及其成员相关的活动',
  org_block: '与组织中被阻止人员相关的活动',
  package: '与 GitHub Packages 有关的活动',
  page_build: '表示尝试构建一个 GitHub Pages 站点，无论是否成功',
  ping: '当您创建新的 web 挂钩时，我们将向您发送一个简单的 ping 事件，让您知道您已正确设置 web 挂钩',
  project_card: '与项目卡有关的活动',
  project_column: '与项目板中的列相关的活动',
  project: '与项目板有关的活动',
  public: '当私有仓库公开时',
  pull_request: '与拉取请求相关的活动',
  pull_request_review: '与拉取请求审查相关的活动',
  pull_request_review_comment: '与拉取请求统一差异中的拉取请求审查评论相关的活动',
  push: '提交代码',
  release: '与发行版相关的活动',
  repository_dispatch: '当 GitHub 应用程序 将 POST 请求发送到“创建仓库分发事件”端点时，此事件发生',
  repository: '与仓库相关的活动',
  repository_import: '与导入到 GitHub 的仓库相关的活动',
  repository_vulnerability_alert: '与仓库中的安全漏洞警报相关的活动',
  secret_scanning_alert: '与仓库中的密码扫描警报相关的活动',
  security_advisory: '与安全通告相关的活动',
  sponsorship: '与赞助列表相关的活动',
  star: '与标星仓库相关的活动',
  status: '当 Git 提交的状态发生更改时',
  team: '与组织的团队相关的活动',
  team_add: "当仓库被添加到团队时",
  watch: '当有人标星仓库时',
  workflow_dispatch: '当有人触发 GitHub 上的工作流程运行或将 POST 请求发送到“创建工作流程分发事件”端点时，此事件发生',
  workflow_run: '当 GitHub Actions 工作流程运行被请求或完成时',
}