function:
  runtime: nodejs12
oss:
  bucketName: my-bukect-01
  events:
    - oss:ObjectCreated:*
  filter:
    key:
      Prefix: source/
      Suffix: .png
      Target: target/
http:
  authType: anonymous
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - HEAD
