function:
  runtime: nodejs12
oss: []
http:
  - authType: anonymous
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - HEAD
scheduler:
  - cronExpression: 0 0 8 * * *
    enable: true
    payload: awesome-fc
