name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: lerna bootstrap
      - run: lerna run build
#       - run: lerna publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}
