http:
  authType: anonymous
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - HEAD
scheduler:
  cronExpression: 0 0 8 * * *
  enable: true
  payload: serveless dk
oss:
  events:
    - oss:ObjectCreated:*
  bucketName: my-bukect-01
  filter:
    Key:
      Prefix: source/
      Suffix: .png
